# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading
Read the documentation for `torch.Tensor` and `torch.cuda`.

In [7]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.

In [8]:
import torch
random_tensor = torch.rand(size=(7, 7))
random_tensor

tensor([[0.5932, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038],
        [0.6511, 0.7745, 0.4369, 0.5191, 0.6159, 0.8102, 0.9801],
        [0.1147, 0.3168, 0.6965, 0.9143, 0.9351, 0.9412, 0.5995],
        [0.0652, 0.5460, 0.1872, 0.0340, 0.9442, 0.8802, 0.0012],
        [0.5936, 0.4158, 0.4177, 0.2711, 0.6923, 0.2038, 0.6833],
        [0.7529, 0.8579, 0.6870, 0.0051, 0.1757, 0.7497, 0.6047],
        [0.1100, 0.2121, 0.9704, 0.8369, 0.2820, 0.3742, 0.0237]])

### 3. Perform a matrix multiplication with another random tensor `(1, 7)`.

In [9]:
rand_tensor = torch.rand(size=(1, 7))
result = torch.mm(random_tensor, rand_tensor.T)
result

tensor([[1.2239],
        [2.0847],
        [1.9002],
        [0.9408],
        [1.5213],
        [1.3606],
        [0.8780]])

### 4. Set the random seed to 0 and repeat 2 & 3.

In [10]:
torch.manual_seed(0)
random_tensor = torch.rand(size=(7, 7))
rand_tensor = torch.rand(size=(1, 7))
result = torch.mm(random_tensor, rand_tensor.T)
result, result.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Set GPU random seed to 1234.

In [11]:
torch.cuda.manual_seed(1234)
tensor = torch.tensor([2, 3], device='cpu')
tensor.device

device(type='cpu')

### 6. Create two random tensors of shape `(2, 3)` on GPU.

In [12]:
torch.manual_seed(1234)
device = 'cuda' if torch.cuda.is_available() else 'cpu'
tensor_a = torch.rand(size=(2, 3), device=device)
tensor_b = torch.rand(size=(2, 3), device=device)
print(f'Device: {device}')
print(tensor_a, tensor_b)

Device: cpu
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])


### 7. Perform matrix multiplication on tensors from 6.

In [13]:
result = torch.mm(tensor_a, tensor_b.T)
result, result.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))

### 8. Find max and min values of the result.

In [14]:
torch.max(result), torch.min(result)

(tensor(0.5617), tensor(0.3647))

### 9. Find max and min indices.

In [15]:
print(result.argmax())
print(result.argmin())

tensor(3)
tensor(0)


### 10. Create a random tensor `(1,1,1,10)` and remove all 1 dimensions.

In [ ]:
torch.manual_seed(7)
x = torch.rand(size=(1, 1, 1, 10))
print(x, x.shape)
x_squeezed = x.squeeze()
print(x_squeezed, x_squeezed.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
